### ISSUE TITLE
在 css 裡放 url(path/to/image.png) 會被冠上 css 的 public path

### ISSUE THREAD

**Issue by wesley100002001** [watchout-tw/park#1]
本來該是 `/static/img/xxx.png`
會變成 `/static/css/static/img/xxx.png`
現在的 workaround 是把圖檔 encode 進 url 的檔案限制調大，從 10000 -> 100000
在 `webpack.base.conf` 檔案裡
```
use: [{
  loader: 'url-loader',
  options: {
    limit: 8192
  }
}]
```

**Comment by chihaoyo** [comment]
Markdown fail? 😆

**Comment by chihhhhhao** [comment]
Found this: https://github.com/webpack-contrib/css-loader/issues/256 about creating alias in webpack con gif & using `~` in CSS. Doesn’t help with this issue but nice to know.

**Comment by chihhhhhao** [comment]
“Handling static assets” for `vue init webpack`: https://vuejs-templates.github.io/webpack/static.html

**Comment by chihhhhhao** [comment]
失敗的例子在這裡：https://ask-vue-webpack.watchout.tw/ 首頁大圖消失了 😢

**Comment by chihhhhhao** [comment]
暫時的解決方法：大圖放在跟 `/src` 平行的 `/static` 裡，CSS裡用 `/static/path/to/image.png` 這樣就不會被 `*-loader` parse。

**Comment by chihhhhhao** [comment]
先close好了 ❤️
